### ISSUE TITLE
[BUG] /cleardispatchblips only removes blips and not the radius.

### ISSUE THREAD

**Issue by Veolene** [Project-Sloth/ps-dispatch#117]
like the title says, the /cleardispatchblips only removes blips and not the radius. Sometimes the blip has a radius attached with it, like so

![image](https://user-images.githubusercontent.com/53438206/222975141-d97c11b0-7ccb-45f2-8f4f-47254976dee0.png)

after using the command /cleardispatchblips the following happens:

![image](https://user-images.githubusercontent.com/53438206/222975151-c3a98297-d6ab-402b-841e-c572763516f4.png)

only the blips gets removed and the radius attached to the blip remains.

the bug is that the blip gets removed but the attached radius remains on the map.

**Comment by LeSiiN** [comment]
That does happen because i added the radius stuff some time ago, and didnt check if the command does his job or not, im trying to fix it

**Comment by Veolene** [comment]
I saw your PR, blips without a radius output the following error:

https://i.imgur.com/YKkH5A0.png

**Comment by MonkeyWhisper** [comment]
Latest PR fixes this issue
