### ISSUE TITLE
Autotheft alerts are not implemented

### ISSUE THREAD

**Issue by BackSH00TER** [Project-Sloth/ps-dispatch#118]
In the config there is an option for `Config.Enable.Autotheft`, however there is actually no implementation for Autotheft alerts (at least I was unable to find them)

**Comment by MonkeyWhisper** [comment]
Yeah, that was part of the original script because this script was completely rewritten, that config does not exist anymore as default on this version, instead players will need to use the exports.

**Comment by DonHulieo** [comment]
I’ve reimplemented these is in my latest PR as I believe I was the one who wrote them out. Always planned to PR and reimplement them, also added auto Alerts for CarJacking, (triggered separately).

**Comment by MonkeyWhisper** [comment]
You are right, that was part of the original PR made. Sorry, too much to keep track off. 
This is now resolved on latest PR pushed
