### ISSUE TITLE
MDT Files not found error

### ISSUE THREAD

**Issue by Kingsman40** [Project-Sloth/ps-dispatch#122]
Hello,

It seems none of the files below are not in the ui folder. I can only assume that is why the MDT won't open when I type /mdt?

[    resources:ps-mdt] Warning: could not find file `ui/dmv.html` (defined in fxmanifest.lua:25)
[    resources:ps-mdt] Warning: could not find file `ui/bolos.html` (defined in fxmanifest.lua:25)
[    resources:ps-mdt] Warning: could not find file `ui/incidents.html` (defined in fxmanifest.lua:25)
[    resources:ps-mdt] Warning: could not find file `ui/penalcode.html` (defined in fxmanifest.lua:25)
[    resources:ps-mdt] Warning: could not find file `ui/reports.html` (defined in fxmanifest.lua:25)
[    resources:ps-mdt] Warning: could not find file `ui/warrants.html` (defined in fxmanifest.lua:25)

**Comment by LeSiiN** [comment]
why do you post that in the wrong script?

**Comment by Kingsman40** [comment]
Sorry, it was a mistake. Thought I was on the ps-mdt git. My apologies.
