### ISSUE TITLE
Bug: Checking for IsDispatchJob which does not exist

### ISSUE THREAD

**Issue by BackSH00TER** [Project-Sloth/ps-dispatch#140]
In sv_main.lua there is a check for `IsDispatchJobs`. This variable no longer exists, it was removed in this PR: https://github.com/Project-Sloth/ps-dispatch/pull/126/files . 

```
RegisterCommand('togglealerts', function(source, args, user)
	local source = source
	if IsDispatchJob then
		TriggerClientEvent('dispatch:manageNotifs', source, args[1])
	end
end)
```

Looks like `Config.AuthorizedJobs.FirstResponder.Check(Player.PlayerData)` may be the updated check that should be used here instead? @DonHulieo, does this seem like the correct check (asking since you made the above changes)?

**Comment by DonHulieo** [comment]
Damn g, sure like tagging me 😂.
> 
> Looks like `Config.AuthorizedJobs.FirstResponder.Check(Player.PlayerData)` may be the updated check that should be used here instead? @DonHulieo, does this seem like the correct check (asking since you made the above changes)?

That would be the correct way to implement the check function, it must have been missed when I pushed initially.
