### ISSUE TITLE
FirstResponder check

### ISSUE THREAD

**Issue by BackSH00TER** [Project-Sloth/ps-dispatch#141]
I've found that the FirstResponder.check function does not work. It is always returning true because PlyData.job.type is a field that does not exist.

I have not updated qbcore for my server in a while, so my first question is `job.type` a standard field shipped with qb core?
If yes, then this is a bug on my end and I need to update qbcore 
If no, this will cause the FirstResponder check to not work for any players using standard qbcore.

Here is the code I'm referring to in the config
```
FirstResponder = { -- do not touch, this is a combined job checking function for emergency services (police and ems)
        Check = function(PlyData)
            PlyData = PlyData or QBCore.Functions.GetPlayerData()
            
// THIS IS THE LINE THAT WILL ALWAYS GET HIT BECAUSE PlyData.job.type is an undefined field
            if not PlyData or (PlyData and (not PlyData.job or not PlyData.job.type))  then return false end
            
local job, jobtype = PlyData.job.name, PlyData.job.type
            if Config.AuthorizedJobs.LEO.Check(PlyData, jobtype, job) or Config.AuthorizedJobs.EMS.Check(PlyData, jobtype, job) then return true end            
        end
    }
```

If job.type is not a standard qbcore field, then we should update the code to gracefully handle working around this. Additionally we should update the readme on what is expected to be added to support this.

**Comment by BackSH00TER** [comment]
@DonHulieo I see that you had added these checks. Do you know if `job.type` is something custom?

**Comment by DonHulieo** [comment]
> @DonHulieo I see that you had added these checks. Do you know if `job.type` is something custom?

No, you need to update your core. It’s been a part of QBCore for a better part of 6 months.

**Comment by BackSH00TER** [comment]
Oh lordy haha. I probably need to start pushing all my custom changes to qb core so it gets easier to pull updates from them
