### ISSUE TITLE
QS-phone compatibility

### ISSUE THREAD

**Issue by UrDay2Die** [Project-Sloth/ps-dispatch#151]
QS-phone adds multiple phone items, if I add them it says that I dont have a phone when I do a /911. How do I add more then one phone Item to the script ?

**Comment by MonkeyWhisper** [comment]
Garbage ass phone

**Comment by UrDay2Die** [comment]
Garbage ass support

**Comment by MonkeyWhisper** [comment]
> Garbage ass support

Skill issue dude, get better 🤣
