### ISSUE TITLE
Dispatchs don't show in MDT "Recents Calls"

### ISSUE THREAD

**Issue by b-bgomes** [Project-Sloth/ps-dispatch#161]
With the new version od Dispatch, when a call is called appers in screen dispatch, but not when u open MDT
Yes, i have the new version of MDT

**Comment by MoneSuper** [comment]
are you sure cause works fine my end?

**Comment by b-bgomes** [comment]
Hi, yeah, i'm sure, no changes has made, no error, just doesn't show in MDT
![image](https://github.com/Project-Sloth/ps-dispatch/assets/97984058/cf05e8c8-5fd8-4754-9c97-7ea6736ae660)
