### ISSUE TITLE
[SUGGESTION] Built in vehicle registration system

### ISSUE THREAD

**Issue by nggcasey** [Project-Sloth/ps-dispatch#167]
Create a built in vehicle registration system where players can go and pay registration on their vehicles, with registration expiry dates that show up on the MDT.

This could be made compatible with the plate reader too therefore creating more interactions with cops/civs.

**Comment by LeSiiN** [comment]
we're not taking suggestions anymore, its opensource, if u want to add it, do it and then make a PR
