### ISSUE TITLE
Ps-Dispatch V2 - Reliable Network Event Overflow

### ISSUE THREAD

**Issue by demetridigital** [Project-Sloth/ps-dispatch#169]
If you press your horn multiple times (Pressing E button) and an alert comes up it tries to set the way point, but if you press it too many times it gives you this error.
 
![FiveM_b2944_GTAProcess_EdxGOpjPDx](https://github.com/Project-Sloth/ps-dispatch/assets/113472737/485566a1-1092-42bb-96ae-f8a33c197453)

**Comment by MonkeyWhisper** [comment]
How about DO NOT SPAM IT?

**Comment by demetridigital** [comment]
Dont spam the horn while in a cop chase? that make sense. was just simply letting yall know it kicks people.
