### ISSUE TITLE
Waypoint set for different job call

### ISSUE THREAD

**Issue by lenzh** [Project-Sloth/ps-dispatch#184]
Person 1: Is Police, and receives a Police-Dispatch Call.
Person 2: Is Ambulance, and receives a Ambulance-Dispatch Call.

Person 2 is pressing [E], and gets the Waypoint for Latest call, but it doesn't filter Calls for jobs. So person 2 gets Waypoint for Police-Dispatch Call etc...

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-dispatch/pull/181
