### ISSUE TITLE
Console spam Error

### ISSUE THREAD

**Issue by lenzh** [Project-Sloth/ps-dispatch#185]
![image](https://github.com/Project-Sloth/ps-dispatch/assets/9503151/bc552a51-65ee-4cb4-9564-740669160654)

**Comment by MonkeyWhisper** [comment]
Bug confirmed

**Comment by OK1ez** [comment]
add a callback in all the RegisterNUICallback

Example: 
![image](https://github.com/Project-Sloth/ps-dispatch/assets/87883296/628e88f0-74be-4df7-a639-c1253d56382b)

**Comment by LeSiiN** [comment]
https://github.com/Project-Sloth/ps-dispatch/pull/210
