### ISSUE TITLE
when debug enabled ems can see all calls for leo

### ISSUE THREAD

**Issue by redpanda19** [Project-Sloth/ps-dispatch#192]

**Comment by redpanda19** [comment]
https://cdn.discordapp.com/attachments/929246504579903541/1167093971948933200/image.png?ex=654cdff6&is=653a6af6&hm=fa59090e8767bc373f9617ddf206bd57b49501b6749c8379bc988cf913a0cd06&

**Comment by MonkeyWhisper** [comment]
Because is debugging?

**Comment by redpanda19** [comment]
yea
