### ISSUE TITLE
ps-dispatch not showing alerts

### ISSUE THREAD

**Issue by 1Merror-error** [Project-Sloth/ps-dispatch#213]
i have the core fully updated but still the alerts are not working they workedd for a while but when i change or add lil things to the core from other scripts make the dispatch not work

**Comment by 1Merror-error** [comment]
im not opening this issue for support just to let u know something maight be wrong or idk but whatever @MonkeyWhisper

**Comment by MonkeyWhisper** [comment]
This isn't an issue from us, it's an issue from you. 

If you need support, ask in Discord and thank you

**Comment by 1Merror-error** [comment]
i try a fresh core install and as soon as u even change or add an item on the core items.lua ps-dispatch stops working and i try telling this issue on the discordd and i got banned
