### ISSUE TITLE
MDT still taking a while time to open after newest version

### ISSUE THREAD

**Issue by NikoClapz19** [Project-Sloth/ps-dispatch#216]
Steps to Reproduce:

1.) Have Dispatch Calls, and then open up the MDT

2.) When ps-dispatch is restarted live in server. The MDT opens up quickly

**Comment by Gnavling** [comment]
![image](https://github.com/Project-Sloth/ps-dispatch/assets/69698024/8d7b3316-6520-4797-89fb-fa2f51e66006)
The delay is up to like a full 10 seconds at times.
