### ISSUE TITLE
Able to set waypoint when off duty

### ISSUE THREAD

**Issue by J4y-uk** [Project-Sloth/ps-dispatch#225]
Hey, So there is no consistence to this but i have noticed when you fly into the city (default off duty) you can toggle E and it sets the waypoint to the last police notification. However, this sometimes stops after toggling your duty but not always.  Video below is a clip as soon as someone fly's into the city and is off duty. 

I'm using the latest version of PS-Dispatch as of today 30/11/2023 GMT

https://youtu.be/sBq8_wwWUog

**Comment by LeSiiN** [comment]
Thank u, i will instantly fix this

**Comment by LeSiiN** [comment]
Do me a favor and test this
https://github.com/Project-Sloth/ps-dispatch/compare/main...LeSiiN:ps-dispatch:isonduty-check
if this simple line fixes ur issue, i will PR it
