### ISSUE TITLE
American Style State Codes changing to British UK 999 Codes

### ISSUE THREAD

**Issue by ChlxeThomson** [Project-Sloth/ps-dispatch#238]
<img width="1196" alt="Screenshot 2023-12-10 021847" src="https://github.com/Project-Sloth/ps-dispatch/assets/58238399/d29e7a85-f968-4f58-b024-2e53d00dc51b">

HOW DO I CHANGE THIS TO SAY BRITISH UK OF 999???

ALSO HOW DO I DISABLE OR MAKE IT THAT THE DISPATCH DOESN;T GIVE CALLS FOR POLICE FIRING THEIR GUNS?

**Comment by LeSiiN** [comment]
Why would u open a Issue for a simple support question ?

Join our discord and link your discord with github, then i'll help u there
