### ISSUE TITLE
Alerts that contain a CamId are inconsistent

### ISSUE THREAD

**Issue by TechnoBehemoth** [Project-Sloth/ps-dispatch#241]
Some alerts flow through and show a Cam ID, others do not. Confirmed that the actual ID is fed through the script all the way up to the .JS file that actually shows the notification for police officers.

**Comment by MonkeyWhisper** [comment]
I don't see the problem? Not all alerts needs Cams ID. 

Send more info with correct bug report.

**Comment by TechnoBehemoth** [comment]
As per the title of the error upon testing, **all** alerts that were sent contained a camID. but only some show the actual ID on the notification widget.
