### ISSUE TITLE
f8 console job error

### ISSUE THREAD

**Issue by djontop** [Project-Sloth/ps-dispatch#249]
![image](https://github.com/Project-Sloth/ps-dispatch/assets/107875648/77387df9-d5ae-47b9-9872-aa760c2bf256)
![image](https://github.com/Project-Sloth/ps-dispatch/assets/107875648/842c02f4-c6a6-49ed-9daa-0d52eab6ca16)

**Comment by Cfa1987** [comment]
Been having this problem my self

**Comment by RLJB1** [comment]
have you fixed this?
