### ISSUE TITLE
Change to center

### ISSUE THREAD

**Issue by vladyxd** [Project-Sloth/ps-dispatch#256]
Would it be possible to move alerts and dispatch to center? or at least to right? or make it a config. It messes up if you want to put something on the top-right side.
![image](https://github.com/Project-Sloth/ps-dispatch/assets/41295778/ddfb1e36-5cc6-4c64-8e24-eec481b5f492)
![image](https://github.com/Project-Sloth/ps-dispatch/assets/41295778/e6ca5c11-2964-4aa4-9e29-60591ed7fcb1)

or to be on left side, like here. but then it would cover the chat, so idk.
![image](https://github.com/Project-Sloth/ps-dispatch/assets/41295778/d512431b-7da8-4ab6-bd0e-ba93202c8d20)

even with short alerts is weird, so I'd appreaciate it.

**Comment by MonkeyWhisper** [comment]
You can do it, open source.

**Comment by AntMars008** [comment]
Holy shit, this guy (MoneyWisperer) is a sad excuse for a human being...SOP is to close all queries, requests, and bug reports, or he'll tell you "Do it yourself", because he can't fix anything himself.

**Comment by MonkeyWhisper** [comment]
> Holy shit, this guy (MoneyWisperer) is a sad excuse for a human being...SOP is to close all queries, requests, and bug reports, or he'll tell you "Do it yourself", because he can't fix anything himself.

Says the guy hiding behind an alt like a little pussy, All talk no action, piece of shit dumb ass.
