### ISSUE TITLE
dispatch

### ISSUE THREAD

**Issue by BeamerFPSYT** [Project-Sloth/ps-dispatch#258]
hello im curious is there anyway to turn off the dispatch is alerting people ghost punching and its alerting like locals stealing other vehicles not playing doing it

**Comment by AntMars008** [comment]
Holy shit, this guy (MoneyWisperer) is a sad excuse for a human being...SOP is to close all queries, requests, and bug reports, or he'll tell you "Do it yourself", because he can't fix anything himself.
