### ISSUE TITLE
dispatch alerts everything

### ISSUE THREAD

**Issue by BeamerFPSYT** [Project-Sloth/ps-dispatch#259]
i can swing in the air and police get alerted and my ticket got closed no reply???

**Comment by AntMars008** [comment]
Holy shit, this guy (MoneyWisperer) is a sad excuse for a human being...SOP is to close all queries, requests, and bug reports, or he'll tell you "Do it yourself", because he can't fix anything himself.

**Comment by AntMars008** [comment]
Holy shit, this guy (MoneyWisperer) is a sad excuse for a human being...SOP is to close all queries, requests, and bug reports, or he'll tell you "Do it yourself", because he can't fix anything himself.
