### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by OmarAlhaji** [Project-Sloth/ps-dispatch#264]
I installed ps-dispatch and ps-mdt and linked them to the database and also linked them to the scripts related to thefts, but the notifications dont' work. What is the reason? I want help, please.

ox_lib last update installed.

**Comment by AntMars008** [comment]
Holy shit, this guy (MoneyWisperer) is a sad excuse for a human being...SOP is to close all queries, requests, and bug reports, or he'll tell you "Do it yourself", because he can't fix anything himself.
