### ISSUE TITLE
"Waypoint Set" when pressing E

### ISSUE THREAD

**Issue by thaibossaw** [Project-Sloth/ps-dispatch#275]
Even if an alert is not displayed on screen, but there has been an alert previously, pressing E will set a waypoint to the alert.

If I ignore an alert, and later am interacting with something completely unrelated, I get "Waypoint Set".

On my server, there is a diving job where you're constantly pressing E to open loot. This means I get "Waypoint Set" over and over again.

Could we make it so that the E button only sets a waypoint within a certain timeframe of the alert being displayed please? That way if I ignore an alert, it won't keep trying to set the waypoint later.

**Comment by LeSiiN** [comment]
Thats exactly like it was intended, to only allow u to press the waypoint when the alert is shown on screen, thats weird

**Comment by LeSiiN** [comment]
tested rn with the most recent ox_lib and dispatch

https://youtu.be/p7eriz7Vaw4

working fine for me, spamming e the whole video

**Comment by thaibossaw** [comment]
I'll do some more testing when I get home from work this evening and see if I can debug what's causing it on my end. Thanks, will update you as soon as I know more.
