### ISSUE TITLE
Hunting

### ISSUE THREAD

**Issue by broonib** [Project-Sloth/ps-dispatch#281]
Hunting blip showing on map 
![image](https://github.com/Project-Sloth/ps-dispatch/assets/170963868/44dfd463-a6e2-406c-b555-32a42dda7812)

**Comment by MonkeyWhisper** [comment]
So what?

**Comment by broonib** [comment]
No sure why your being liek that but any way. I thought it was a bug as I cant seem to find away to switch it off. As I don't see why any one would want that showing if they aren't hunting?
