### ISSUE TITLE
storerobbery and other robberys camid not showing

### ISSUE THREAD

**Issue by BerlinDev-Five** [Project-Sloth/ps-dispatch#68]
please help me
![Screenshot 2022-06-09 160522](https://user-images.githubusercontent.com/64470282/172829038-c0fa799b-db73-4262-bb83-bd33063689a2.png)

**Comment by parham-tehrani** [comment]
how did you even make it work for jewelery? i've been working on that couldnt make it work...
and when you put the export in jewelery , right before that add
local camId = "31-34"

**Comment by MonkeyWhisper** [comment]
Join discord for support. 

https://discord.gg/projectsloth
