### ISSUE TITLE
Config.OnDutyOnly breaks top-right UI alerts.

### ISSUE THREAD

**Issue by maguhd** [Project-Sloth/ps-dispatch#91]
When Config.OnDutyOnly = true, the cops(even if they on or off duty) don't get the top-right alerts UI (only sound), but they get it in the MDT.
I've set Config.OnDutyOnly = false and it works. So I guess it's a lingering issue where if you enable the onduty it breaks the UI alert top-right.

For anyone that want the onduty feature to work:

Replace this line in cl_main.lua
```lua
if IsValidJob(sNotificationData['job']) and CheckOnDuty() then
```
with:
```lua
if IsValidJob(sNotificationData['job']) and ASCore.Functions.GetPlayerData().job.onduty then
```
and you'll be good to go untill they fix it.

I tried:
```lua
if IsValidJob(sNotificationData['job']) and PlayerJob.onduty then
```
but it doesn't work.

**Comment by MonkeyWhisper** [comment]
Send a PR, but make sure to edit the proper Core...
